name: Nuget

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2.0.
      - name: Build the Docker image
        run: docker build -f Dockerfile -t HandyOrg/hcbuild .
      - name: Run the Docker image
        run: docker run --rm HandyOrg/hcbuild --version
